"""Shared dependencies: Jinja2 templates, global template context, rate limiting."""
from __future__ import annotations

import logging
import secrets
import time
from collections import defaultdict, deque
from pathlib import Path

from fastapi import HTTPException, Request
from fastapi.templating import Jinja2Templates

from . import crud, i18n
from .config import settings

log = logging.getLogger("casagracia.ratelimit")

BASE_DIR = Path(__file__).resolve().parent
templates = Jinja2Templates(directory=str(BASE_DIR / "templates"))


def cop(value: int) -> str:
    """Format an integer COP amount as $1.234.567."""
    try:
        return "$" + f"{int(value):,}".replace(",", ".")
    except (ValueError, TypeError):
        return "$0"


templates.env.filters["cop"] = cop


def webp(path: str) -> str:
    """Map an image path to its WebP sibling (generated by tools/optimize_images.py).
    e.g. '/static/img/fb_hd/x.jpg' -> '/static/img/fb_hd/x.webp'."""
    if not path:
        return path
    low = path.lower()
    for ext in (".jpg", ".jpeg", ".png"):
        if low.endswith(ext):
            return path[: -len(ext)] + ".webp"
    return path


templates.env.filters["webp"] = webp

# Values available in every template.
GLOBAL_CONTEXT = {
    "hotel": {
        "name": settings.hotel_name,
        "address": settings.hotel_address,
        "phone": settings.hotel_phone,
        "whatsapp": settings.hotel_whatsapp,
        "email": settings.hotel_email,
        "instagram": settings.hotel_instagram,
        "facebook": settings.hotel_facebook,
        "lat": settings.hotel_lat,
        "lng": settings.hotel_lng,
    },
    "currency": settings.currency,
    # Absolute site origin (no trailing slash) for canonical URLs, OpenGraph
    # tags and sitemap/JSON-LD. Set BASE_URL in production (e.g. the Vercel URL).
    "base_url": settings.base_url.rstrip("/"),
    # Cache-busting token for /static assets. Changes on every server start, so
    # browsers always fetch the latest CSS/JS after a deploy/restart.
    "asset_v": int(time.time()),
}


def is_valid_admin_token(token: str) -> bool:
    """Constant-time check of an admin token. The placeholder default is always
    rejected, so an unconfigured deploy can't be administered by guessing it."""
    expected = settings.admin_token
    if not expected or expected == "change-me-admin-token" or not token:
        return False
    return secrets.compare_digest(token, expected)


def t_for(request: Request):
    """Return a translate function bound to the request's language (for routes)."""
    lang = i18n.get_lang(request)
    return lambda s, **kw: (i18n.t(s, lang).format(**kw) if kw else i18n.t(s, lang))


def money(cop, lang: str) -> str:
    """Localized price: COP in Spanish, converted USD in English."""
    cop = int(cop or 0)
    if lang == "en":
        return "US$" + f"{round(cop / settings.usd_to_cop):,}"
    return "$" + f"{cop:,}".replace(",", ".") + " COP"


def render(request: Request, template: str, **ctx):
    lang = i18n.get_lang(request)
    base = {
        **GLOBAL_CONTEXT,
        "lang": lang,
        "t": lambda s: i18n.t(s, lang),
        "room_name": lambda r: i18n.room_name(r, lang),
        "room_desc": lambda r: i18n.room_desc(r, lang),
        "money": lambda cop: money(cop, lang),
        "money_cfg": {"lang": lang, "rate": settings.usd_to_cop,
                      "currency": "USD" if lang == "en" else "COP"},
        "js_i18n": i18n.js_bundle(lang),
    }
    return templates.TemplateResponse(request, template, {**base, **ctx})


# --- Rate limiter ----------------------------------------------------------
# Distributed (shared Postgres counter) so it works across the several
# serverless instances Vercel may run. If the DB is unreachable it FAILS OPEN
# to a per-instance in-process counter, so the site never breaks because of it.
_hits: dict[str, deque] = defaultdict(deque)
_TOO_MANY = HTTPException(status_code=429,
                          detail="Demasiadas solicitudes. Intenta en un momento.")


def _client_ip(request: Request) -> str:
    # Behind Vercel's proxy the real client is in X-Forwarded-For.
    fwd = request.headers.get("x-forwarded-for", "")
    if fwd:
        return fwd.split(",")[0].strip()
    return request.client.host if request.client else "anon"


def _in_process(key: str, limit: int) -> None:
    now = time.time()
    q = _hits[key]
    while q and q[0] < now - 60:
        q.popleft()
    if len(q) >= limit:
        raise HTTPException(status_code=429, detail=_TOO_MANY.detail)
    q.append(now)


async def rate_limit(request: Request, max_per_minute: int | None = None) -> None:
    """Allow up to `max_per_minute` requests per client per tier each minute."""
    limit = max_per_minute or settings.rate_limit_per_minute
    ip = _client_ip(request)
    # Separate counter per limit tier (e.g. reads vs. booking vs. reviews).
    key = f"{ip}:{limit}"
    try:
        from .database import SessionLocal
        async with SessionLocal() as s:
            count = await crud.hit_rate_limit(s, key)
        if count > limit:
            raise _TOO_MANY
        return
    except HTTPException:
        raise
    except Exception:
        # DB hiccup / table missing: degrade to the in-process limiter.
        log.warning("rate limiter DB unavailable; using in-process fallback")
        _in_process(key, limit)
